// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByrxFQ-sbVOVSqxXazWdt-gb05u4pKUho',
    appId: '1:806455577889:web:0e52ef8962b0789e03c260',
    messagingSenderId: '806455577889',
    projectId: 'takecare-e6ec8',
    authDomain: 'takecare-e6ec8.firebaseapp.com',
    storageBucket: 'takecare-e6ec8.appspot.com',
    measurementId: 'G-J5N2C35S0S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmR9SRpOuMsRhQiJknp_CybF73X4-9u6M',
    appId: '1:806455577889:android:c1a00ded6fa144df03c260',
    messagingSenderId: '806455577889',
    projectId: 'takecare-e6ec8',
    storageBucket: 'takecare-e6ec8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD14f74QBlxKOuDS7NUr97ArtzSsr5N0Lg',
    appId: '1:806455577889:ios:8f752ecd6941c5e803c260',
    messagingSenderId: '806455577889',
    projectId: 'takecare-e6ec8',
    storageBucket: 'takecare-e6ec8.appspot.com',
    iosClientId: '806455577889-okn4djgvcpu49l9k5ppoa9o34bkc30qq.apps.googleusercontent.com',
    iosBundleId: 'com.example.takeCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD14f74QBlxKOuDS7NUr97ArtzSsr5N0Lg',
    appId: '1:806455577889:ios:8f752ecd6941c5e803c260',
    messagingSenderId: '806455577889',
    projectId: 'takecare-e6ec8',
    storageBucket: 'takecare-e6ec8.appspot.com',
    iosClientId: '806455577889-okn4djgvcpu49l9k5ppoa9o34bkc30qq.apps.googleusercontent.com',
    iosBundleId: 'com.example.takeCare',
  );
}
